### ISSUE TITLE
Enable CORS headers on openapi endpoint

### ISSUE THREAD

**Issue by WillemElbers** [clarin-eric/DOGlib#13]
Please enable CORS headers (`Access-Control-Allow-Origin: *` or something more specific) to allow loading the JSON from external swagger ui deployments.

One such deployment will likely be available from https://infra.clarin.eu/apis soon, see https://github.com/clarin-eric/infra.clarin.eu_static-files/pull/3

**Comment by MichalGawor** [comment]
N/A to DOGlib.
Moved issue to [DOGapp](https://github.com/clarin-eric/DOGapp/issues/5)
