### ISSUE TITLE
Overview of supported repositories

### ISSUE THREAD

**Issue by dietervu** [clarin-eric/DOGlib#26]
It would be good to have an easy to browse overview of supported repositories. Could be a markdown file in github or a webpage for the web service, or both.

**Comment by MichalGawor** [comment]
Create script for dumping registered repositories into .csv with human readible repository description.
Include the table in README. Do not include monitoring of the repository status on the side of DOGlib - only which repositories have their config file. 

Browsable status of supported repositories and logging moved to [DOGapp#15](https://github.com/clarin-eric/DOGapp/issues/15)

**Comment by MichalGawor** [comment]
Methods for status overview added to DOG class, status check logic TODO in DOGapp
