### ISSUE TITLE
Mark repo config files as licensed under CC0 

### ISSUE THREAD

**Issue by dietervu** [clarin-eric/DOGlib#27]
The grant agreement of ATRIUM requires all metadata to be released as CC0.

**Comment by MichalGawor** [comment]
For now agreed to license repository config files under GPLv3 together with the source code. To be further discussed.

**Comment by dietervu** [comment]
I discussed this option with @MichalGawor and changing the license of the Doglib repository configuration files would be complicated, since they are included in the wheel distribution which is published under the default license for CLARIN software: GPL version 3. In order to avoid double licensing we will keep them under GPL v3 too. In this case it can be argued that the configuration files are rather source code than metadata.
